// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjk-MhpyXJdDoVVcC-BRBakuX_-U9kjus',
    appId: '1:568379947403:web:3b4bdc1528366f45eb978e',
    messagingSenderId: '568379947403',
    projectId: 'my-messenger-16',
    authDomain: 'my-messenger-16.firebaseapp.com',
    storageBucket: 'my-messenger-16.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRwdzOMN9mFp0yU9DlaAhZpmMZopPFhQE',
    appId: '1:568379947403:android:28ffa69336732cf9eb978e',
    messagingSenderId: '568379947403',
    projectId: 'my-messenger-16',
    storageBucket: 'my-messenger-16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPoYGpD2kYSBE81F44CWAj2nU96UVFjsE',
    appId: '1:568379947403:ios:1b434d3236e4f30aeb978e',
    messagingSenderId: '568379947403',
    projectId: 'my-messenger-16',
    storageBucket: 'my-messenger-16.firebasestorage.app',
    iosBundleId: 'com.example.myMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPoYGpD2kYSBE81F44CWAj2nU96UVFjsE',
    appId: '1:568379947403:ios:1b434d3236e4f30aeb978e',
    messagingSenderId: '568379947403',
    projectId: 'my-messenger-16',
    storageBucket: 'my-messenger-16.firebasestorage.app',
    iosBundleId: 'com.example.myMessenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjk-MhpyXJdDoVVcC-BRBakuX_-U9kjus',
    appId: '1:568379947403:web:f917988c0e6e4d8ceb978e',
    messagingSenderId: '568379947403',
    projectId: 'my-messenger-16',
    authDomain: 'my-messenger-16.firebaseapp.com',
    storageBucket: 'my-messenger-16.firebasestorage.app',
  );
}
